In [4]:
import numpy as np
x = np.array([10,20,30,1])
y = np.array([2,3,4,2])
add = x + y
print(add)

[12 23 34  3]


## trigonometry


In [8]:
sin_val = np.sin(x)
cos_val = np.cos(x)
print(sin_val)          


[-0.54402111  0.91294525 -0.98803162  0.84147098]


In [9]:
# radian to deg

deg = np.rad2deg(x)
print(deg) 

[ 572.95779513 1145.91559026 1718.87338539   57.29577951]


## Understanding Different Log Functions

**For Normal People:** Think of logarithms as "reverse exponents" - they tell you what power you need to raise a number to get another number.

- **log10**: "What power of 10 gives me this number?"
- **log2**: "What power of 2 gives me this number?" 
- **log**: "What power of e (≈2.718) gives me this number?" (natural logarithm)


In [ ]:
# Let's see the difference with simple examples
import numpy as np

# Create a simple array
numbers = np.array([1, 10, 100, 1000])

print("Our numbers:", numbers)
print()

# log10 - base 10 logarithm
log10_result = np.log10(numbers)
print("log10 (base 10):", log10_result)
print("Explanation: 10^0=1, 10^1=10, 10^2=100, 10^3=1000")
print()

# log2 - base 2 logarithm  
log2_result = np.log2(numbers)
print("log2 (base 2):", log2_result)
print("Explanation: 2^0=1, 2^3.32≈10, 2^6.64≈100, 2^9.97≈1000")
print()

# log - natural logarithm (base e ≈ 2.718)
log_result = np.log(numbers)
print("log (natural, base e):", log_result)
print("Explanation: e^0=1, e^2.3≈10, e^4.6≈100, e^6.9≈1000")


In [13]:
# log 
print(x)
base_10 =  np.log10(x)
print(base_10)

[10 20 30  1]
[1.         1.30103    1.47712125 0.        ]


In [14]:
# square root
sqrt = np.sqrt(x)

In [19]:
# sum 
s = np.sum(x)
print(s)

61


In [24]:
#cumulative sum 
cum = np.cumsum(x)
print(cum) 

[10 30 60 61]
