In [26]:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(arr[0,1,2])

6


In [27]:
import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('Last element from 2nd dim: ', arr[1, -1])


Last element from 2nd dim:  10


In [28]:
import numpy as np

arr = np.array([
    [
    [1,2,3], 
    [2,3,4],
    ],
     [
        [6,7,8], 
        [4,6,6]]
     ])

arr4d = np.array([
    # 1st floor
    [
    [1,2,3], 
    [2,3,4],
    ],
    # 2nd floor
     [
        [6,7,8], 
        [4,6,6]],

    #3rd floor 
     [  
        [1,2,3], 
         [2,3,4],
    ]
     ])


print(arr.shape,'Last element from 2nd dim: ', arr4d.shape)

(2, 2, 3) Last element from 2nd dim:  (3, 2, 3)


In [29]:
import numpy as np
arr = np.array([1,2,3],dtype=np.int8)

print(arr.dtype)
arr = arr.astype(np.int16)
print(arr.dtype)

int8
int16


## converting tuple, set, dic into ndarray


In [30]:
import numpy as np
dic = {"a":1, "b":2, "c":3}
keys = dic.keys()
values = dic.values()

print(keys, "nl", values)
key_arr = np.array(list(dic.items()))
print(key_arr, key_arr.dtype, "check", key_arr.ndim,"size",key_arr.size)


dict_keys(['a', 'b', 'c']) nl dict_values([1, 2, 3])
[['a' '1']
 ['b' '2']
 ['c' '3']] <U21 check 2 size 6


In [36]:
arr = np.zeros((2,3, 2), dtype=np.int16)
newArr = np.full_like(arr4d,np.inf, float)
print(newArr, "ls", arr.dtype)


[[[inf inf inf]
  [inf inf inf]]

 [[inf inf inf]
  [inf inf inf]]

 [[inf inf inf]
  [inf inf inf]]] ls int16


## NDArray Generation

In [47]:
arr1 = np.random.rand(2,4)

# int format
arr2 = np.random.randint(1,10, (4,3))

# float format
arr3 = np.random.uniform(2, 8, (2,2))

# from range
arr = np.arange(1,10,1)
mat = arr.reshape(3,3)

print(arr)
print(mat)
print(arr.dtype,"type")
print(arr.ndim,"dimention")
print(arr.shape,"shape")
print(arr.size,"size")


[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
int64 type
1 dimention
(9,) shape
9 size
