In [40]:
import numpy as np
a = np.random.randint(1,10, size=(2,3))
b = np.random.randint(20, 30, size=(1,3))
concatenate = np.concatenate((a,b),axis=0)
print("a\n",a)
print("b\n",b)
print("concate \n", concatenate)

a
 [[6 1 4]
 [3 6 2]]
b
 [[29 25 29]]
concate 
 [[ 6  1  4]
 [ 3  6  2]
 [29 25 29]]


## Transpose matrix

In [44]:

arr = np.array([[10,20,30],
                [30,40]])

transpose = arr.T
print(transpose)

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.